version: '3.3'
services:
  mysql2:
    image: mysql:8.0.20
    restart: always
    environment:
      MYSQL_DATABASE: 'db_ambulance'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'