spring:
  application:
    name: OutpatientService
  main:
    banner-mode: 'OFF'
  datasource:
    url: jdbc:mysql://localhost:3307/db_ambulance
    username: user
    password: password
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL8Dialect
  messages:
    basename: messages # i18n.messages
  liquibase:
    change-log: 'classpath:db/migration/changeLog.xml'
    enabled: true
