insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Сидоров Д.А', '01.01.2001', 'д.Березовка', 1, 'насморк, зуд в глазах', 'появление симптомов при контакте с пыльцой', 'отмечается отечность век', 'аллергия', 1, 1, 0);
insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Петров А.Е.', '05.06.1980', 'д.Петровка', 2, 'головная боль', 'симптомы после умственного перенапряжения', 'сильные пульсирующие боли в области левого глаза', 'мигрень', 3, 0, 0);
insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Ослов И.А.', '16.11.2005', 'д.Ословка', 2, 'Боли и рези при мочеиспускании', 'Жалобы после незащищенных связей', 'состояние отчечное, гиперимированное', 'гонорея', 3, 0, 0);
insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Зайцев Н.Н.', '20.10.1999', 'д.Зайцквка', 3, 'Кашель, насморк, озноб', 'После переохлаждения', 'Температура тела 38.2', 'ОРВ', 1, 0, 0);
insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Мальцев М.М.', '10.05.1991', 'г.Широкий-Лог', 6, 'Изжога, боль в животе', 'после употребления жирной пищи', 'боль в эпигастрии при пальпации', 'Хронический гастрит(обострение)', 1, 0, 0);
insert into PATIENT_CARD(full_name, dob, home_address, num_site, complaints, anamnesis, conditions, diagnosis, recommendations, signature_doc, signature_chief) values ('Дедушкин М.З.', '11.02.1925', 'д.Стариково', 6, 'Жалоб нет', 'не отягощен', 'Удовлетварительное', 'Без патологий, диспансеризация', 2, 0, 0);

insert into RECIPE(preparation, status, note, card_id) values ('цетиризин 10мг. 1 раз в день.', 0, 'нет', 1);
insert into RECIPE(preparation, status, note, card_id) values ('ингаверин 90мг 1 раз в день/7', 0, 'нет', 4);
insert into RECIPE(preparation, status, note, card_id) values ('Омепразол 20мг 2р. в день(утром-вечером)/30дней', 0, 'нет', 5);